{% set name = "fancycompleter" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancycompleter-{{ version }}.tar.gz
  sha256: 5b4ad65d76b32b1259251516d0f1cb2d82832b1ff8506697a707284780757f69

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=8
    - tomli
  run:
    - python
    - pyrepl >=0.11.3  # [py<313]

test:
  source_files:
    - tests
  imports:
    - fancycompleter
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - python
    - pip
    - pytest

about:
  home: https://pypi.org/project/fancycompleter
  license: BSD-3-Clause
  license_family: BSD
  summary: 'colorful Python TAB completion'
  license_file: LICENSE
  description: |
    fancycompleter is a module to improve your experience in Python by adding
    TAB completion to the interactive prompt. It is an extension of the
    stdlib's rlcompleter module.
  doc_url: https://pypi.org/project/fancycompleter
  dev_url: https://github.com/bretello/fancycompleter

extra:
  recipe-maintainers:
    - kynan
    - sodre
    - mariusvniekerk
    - anjos
