{% set name = "fancycompleter" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fancycompleter-{{ version }}.tar.gz
  sha256: 09e0feb8ae242abdfd7ef2ba55069a46f011814a80fe5476be48f51b00247272

build:
  number: 1003
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setupmeta
  run:
    - python
    - pyreadline  # [win]
    - pyrepl >=0.8.2  # [not win] 

test:
  imports:
    - fancycompleter
  commands:  # [not win]
    - pip check  # [not win]
  requires:  # [not win]
    - pip  # [not win]

about:
  home: https://github.com/pdbpp/fancycompleter
  license: BSD
  license_family: BSD
  summary: 'colorful Python TAB completion'
  # license file missing: https://bitbucket.org/antocuni/fancycompleter/issues/5
  # license_file: LICENSE.txt
  description: |
    fancycompleter is a module to improve your experience in Python by adding
    TAB completion to the interactive prompt. It is an extension of the
    stdlib's rlcompleter module.
  doc_url: https://github.com/pdbpp/fancycompleter
  dev_url: https://github.com/pdbpp/fancycompleter

extra:
  recipe-maintainers:
    - kynan
    - sodre
