{% set name = "fancycompleter" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancycompleter-{{ version }}.tar.gz
  sha256: 632b265b29dd0315b96d33d13d83132a541d6312262214f50211b3981bb4fa00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyreadline  # [win]
    - pyrepl >=0.11.3

test:
  imports:
    - fancycompleter
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://pypi.org/project/fancycompleter
  license: BSD-3-Clause
  license_family: BSD
  summary: 'colorful Python TAB completion'
  license_file: LICENSE
  description: |
    fancycompleter is a module to improve your experience in Python by adding
    TAB completion to the interactive prompt. It is an extension of the
    stdlib's rlcompleter module.
  doc_url: https://pypi.org/project/fancycompleter
  dev_url: https://github.com/bretello/fancycompleter

extra:
  recipe-maintainers:
    - kynan
    - sodre
    - mariusvniekerk
